version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:4.0.9-1
    container_name: redis
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:10
    container_name: postgresql
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=gitlab
    - DB_NAME=gitlab
    - DB_EXTENSION=pg_trgm
    ports:
    - "127.0.0.1:5432:5432"

  gitlab:
    restart: always
    image: sameersbn/gitlab:11.6.0
    container_name: gitlab
    depends_on:
    - redis
    - postgresql
    ports:
    - "$DOCKER_HOST_IP:3000:80"
    - "127.0.0.1:3022:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=gitlab
    - DB_NAME=gitlab

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Europe/Athens
    - GITLAB_TIMEZONE=Athens

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=localhost
    - GITLAB_PORT=3000
    - GITLAB_SSH_PORT=3022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=874056E0E705FDBD454B38141E2A943A7DA58F8C73538C64212B3B192CA51696
    - GITLAB_SECRETS_SECRET_KEY_BASE=874056E0E705FDBD454B38141E2A943A7DA58F8C73538C64212B3B192CA51696
    - GITLAB_SECRETS_OTP_KEY_BASE=874056E0E705FDBD454B38141E2A943A7DA58F8C73538C64212B3B192CA51696

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_BACKUP_SCHEDULE=disable
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - IMAP_ENABLED=false
    - OAUTH_ENABLED=false
    extra_hosts:
    - "host.docker.internal:$DOCKER_HOST_IP"    

  haproxy:
    restart: always
    build: haproxy
    container_name: proxy
    ports:
    - 80:80
    extra_hosts:
    - "host.docker.internal:$DOCKER_HOST_IP"